import os
import subprocess
import shutil
from fastapi import FastAPI, UploadFile, Form, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

app = FastAPI(title="Manim Video Generation API")

# Temporary directory to handle asset compilation
RENDER_DIR = "/tmp/manim_render"
os.makedirs(RENDER_DIR, exist_ok=True)

@app.post("/render")
async def render_video(
    code: str = Form(..., description="The complete Python Manim code asset"),
    audio: UploadFile = Form(..., description="The ElevenLabs MP3 voiceover file")
):
    # Unique base naming to prevent collisions on concurrent requests
    base_name = "scene_output"
    script_path = os.path.join(RENDER_DIR, f"{base_name}.py")
    audio_path = os.path.join(RENDER_DIR, f"{base_name}.mp3")
    
    # 1. Write the Manim Python script to disk
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(code)
        
    # 2. Write the incoming ElevenLabs audio binary stream to disk
    with open(audio_path, "wb") as f:
        shutil.copyfileobj(audio.file, f)
        
    try:
        # 3. Execute Manim CLI compilation
        # -qm: Quality Medium (1080p, 30fps) - ideal balance for shorts generation speed
        # --media_dir: Custom output mapping directory
        manim_cmd = [
            "manim", 
            "-qm", 
            "--media_dir", RENDER_DIR, 
            script_path, 
            "MainScene"
        ]
        
        result = subprocess.run(manim_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode != 0:
            raise HTTPException(status_code=400, detail=f"Manim compilation failed: {result.stderr}")
            
        # Locate the compiled video asset generated by Manim
        # Structure defaults to: RENDER_DIR/videos/scene_output/1080p30/MainScene.mp4
        raw_video_path = os.path.join(RENDER_DIR, "videos", base_name, "1080p30", "MainScene.mp4")
        
        if not os.path.exists(raw_video_path):
            raise HTTPException(status_code=500, detail="Video rendered but file output path could not be located.")
            
        # 4. Use FFmpeg to merge the raw video animation with the audio track
        final_output_path = os.path.join(RENDER_DIR, "final_shorts_output.mp4")
        
        ffmpeg_cmd = [
            "ffmpeg", "-y",
            "-i", raw_video_path,
            "-i", audio_path,
            "-c:v", "copy",       # Stream-copy video to bypass expensive re-encoding
            "-c:a", "aac",        # Standardize audio stream format
            "-map", "0:v:0",
            "-map", "1:a:0",
            "-shortest",          # Cuts off video generation if lengths mismatch slightly
            final_output_path
        ]
        
        ffmpeg_result = subprocess.run(ffmpeg_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if ffmpeg_result.returncode != 0:
            raise HTTPException(status_code=500, detail=f"Audio multiplexing failed: {ffmpeg_result.stderr}")
            
        # 5. Return the binary video stream directly back to Make.com
        return FileResponse(final_output_path, media_type="video/mp4", filename="educational_short.mp4")

    except Exception as e:
        if not isinstance(e, HTTPException):
            raise HTTPException(status_code=500, detail=str(e))
        raise e
        
    finally:
        # Cleanup routine hook can be inserted here if persistent storage limits are small
        pass
